=== eea/clms-hrwsi-system/HRWSI_Processing_Routines/HRWSI_Yearly_Processing_Routines/sp_s1s2/let-it-snow-1.11.0/doc/atbd/fsc_config_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "fsc_config_schema.json",
    "properties": {
        "general": {
            "id": "general",
            "properties": {
                "multi": {
                    "default": 10,
                    "description": "Scale input parameters to map reflectance interval (parameters are provided in milli-reflectance but L2A S2 Theia product are between 0 and 10000).",
                    "id": "multi",
                    "title": "The Multi schema.",
                    "type": "integer"
                },
                "mode": {
                    "default": "sentinel2",
                    "description": "Mode used to retrieve clouds : 'sentinel2', 'lasrc', 'sen2cor'",
                    "id": "mode",
                    "title": "The Mode schema.",
                    "type": "string"
                },
                "nb_threads": {
                    "default": 1,
                    "description": "Maximum number of threads use by the program.",
                    "id": "nb_threads",
                    "title": "The Nb_threads schema.",
                    "type": "integer"
                },
                "no_data": {
                    "default": -10000,
                    "description": "No-data value in the input L2A product.",
                    "id": "no_data",
                    "title": "The Nodata schema.",
                    "type": "integer"
                },
                "preprocessing": {
                    "default": false,
                    "description": "Activate the extraction and resampling of the DEM.",
                    "id": "preprocessing",
                    "title": "The Preprocessing schema.",
                    "type": "boolean"
                },
                "ram": {
                    "default": 2048,
                    "description": "Maximum number of RAM memory used by the program.",
                    "id": "ram",
                    "title": "The Ram schema.",
                    "type": "integer"
                }
            },
            "type": "object"
        },
        "vector": {
            "id": "vector",
            "properties": {
                "generate_vector": {
                    "default": true,
                    "description": "Generate vector with snow and cloud masks of the final detection.",
                    "id": "generate_vector",
                    "title": "The Generate_vector schema.",
                    "type": "boolean"
                },
                "generate_intermediate_vectors": {
                    "default": false,
                    "description": "Generate vector masks of the detection (pass 1 and 2 and final result).",
                    "id": "generate_intermediate_vectors",
                    "title": "The generate_intermediate_vectors schema.",
                    "type": "boolean"
                },
                "use_gdal_trace_outline": {
                    "default": true,
                    "description": "Generate vector mask using gdal_trace_outline from gina_tools.",
                    "id": "use_gdal_trace_outline",
                    "title": "The use_gdal_trace_outline schema.",
                    "type": "boolean"
                },
                "gdal_trace_outline_min_area": {
                    "default": 0,
                    "description": "Minimum area to keep in vector mask when using gdal_trace_outline.",
                    "id": "gdal_trace_outline_min_area",
                    "title": "The gdal_trace_outline_min_area schema.",
                    "type": "int"
                },
                "gdal_trace_outline_dp_toler": {
                    "default": 0,
                    "description": "Tolered pixel approximation in vector mask when using gdal_trace_outline (0 no approximation).",
                    "id": "gdal_trace_outline_dp_toler",
                    "title": "The gdal_trace_outline_dp_toler schema.",
                    "type": "int"
                }
            },
            "type": "object"
        },
        "cloud": {
            "id": "cloud",
            "properties": {
                "all_cloud_mask": {
                    "default": 1,
                    "description": "Threshold apply to Theia cloud mask to retrieve a strict cloud mask (greater than all_cloud_mask).",
                    "id": "all_cloud_mask",
                    "title": "The All_cloud_mask schema.",
                    "type": "integer"
                },
                "high_cloud_mask": {
                    "default": 128,
                    "description": "bitmask apply to retrieve high clouds for input mask",
                    "id": "high_cloud_mask",
                    "title": "The High_cloud_mask schema.",
                    "type": "integer"
                },
                "shadow_in_mask": {
                    "default": 32,
                    "description": "bitmask apply to retrieve cloud shadows (for cloud inside the image).",
                    "id": "shadow_in_mask",
                    "title": "The Shadow_in_mask schema.",
                    "type": "integer"
                },
                "shadow_out_mask": {
                    "default": 64,
                    "description": "bitmask apply to retrieve cloud shadows (for cloud outside the image).",
                    "id": "shadow_out_mask",
                    "title": "The Shadow_out_mask schema.",
                    "type": "integer"
                },
                "red_back_to_cloud": {
                    "default": 100,
                    "description": "Minimum value of the red band reflectance to return a non-snow pixel to the cloud mask.",
                    "id": "red_backtocloud",
                    "title": "The Red_backtocloud schema.",
                    "type": "integer"
                },
                "resize_factor": {
                    "default": 12,
                    "description": "Resize factor to produce the down-sampled red band (use for cloud refinement).",
                    "id": "rf",
                    "title": "The Rf schema.",
                    "type": "integer"
                },
                "red_dark_cloud": {
                    "default": 300,
                    "description": "Maximum value of the down-sampled red band reflectance to define a dark cloud pixel.",
                    "id": "red_darkcloud",
                    "title": "The Red_darkcloud schema.",
                    "type": "integer"
                },
                "strict_cloud_mask": {
                    "default": false,
                    "description": "Option that prevent any snow detection within the initial cloud mask. (experimental)",
                    "id": "strict_cloud_mask",
                    "title": "The Strict_cloud_mask schema.",
                    "type": "boolean"
                },
                "rm_snow_inside_cloud": {
                    "default": false,
                    "description": "Trigger the experimental function discarding snow area that are inside in cloud mask.(experimental)",
                    "id": "rm_snow_inside_cloud",
                    "title": "The Rm_snow_inside_cloud schema.",
                    "type": "boolean"
                },
                "rm_snow_inside_cloud_dilation_radius": {
                    "default": 1,
                    "description": "Size in pixel of the dilation radius around the snow area. (experimental)",
                    "id": "rm_snow_inside_cloud_dilation_radius",
                    "title": "The Rm_snow_inside_cloud_dilation_radius schema.",
                    "type": "integer"
                },
                "rm_snow_inside_cloud_threshold": {
                    "default": 0.85,
                    "description": "Minimum fraction of cloudy pixel in the dilated area to discard the snow area. (experimental)",
                    "id": "rm_snow_inside_cloud_threshold",
                    "title": "The rm_snow_inside_cloud_threshold schema.",
                    "type": "float"
                },
                "rm_snow_inside_cloud_min_area": {
                    "default": 5000,
                    "description": "Minimum area (in pixels) for snow areas to execute the cold cloud removal. (experimental)",
                    "id": "rm_snow_inside_cloud_min_area",
                    "title": "The rm_snow_inside_cloud_min_area schema.",
                    "type": "int"
                }
            },
            "type": "object"
        },
        "snow": {
            "id": "snow",
            "properties": {
                "dz": {
                    "default": 100,
                    "description": "Minimum snow fraction in an elevation band to define zs.",
                    "id": "dz",
                    "title": "The Dz schema.",
                    "type": "integer"
                },
                "ndsi_pass1": {
                    "default": 0.4,
                    "description": "Minimum value of the NDSI for the pass 1 snow test.",
                    "id": "ndsi_pass1",
                    "title": "The Ndsi_pass1 schema.",
                    "type": "number"
                },
                "red_pass1": {
                    "default": 200,
                    "description": "Minimum value of the red band reflectance the pass 1 snow test.",
                    "id": "red_pass1",
                    "title": "The Red_pass1 schema.",
                    "type": "integer"
                },
                "ndsi_pass2": {
                    "default": 0.15,
                    "description": "Minimum value of the NDSI for the pass 2 snow test.",
                    "id": "ndsi_pass2",
                    "title": "The Ndsi_pass2 schema.",
                    "type": "number"
                },
                "red_pass2": {
                    "default": 40,
                    "description": "Minimum value of the red band reflectance the pass 2 snow test.",
                    "id": "red_pass2",
                    "title": "The Red_pass2 schema.",
                    "type": "integer"
                },
                "fsnow_lim": {
                    "default": 0.1,
                    "description": "Minimum snow fraction in an elevation band to define zs.",
                    "id": "fsnow_lim",
                    "title": "The Fsnow_lim schema.",
                    "type": "number"
                },
                "fsnow_total_lim": {
                    "default": 0.001,
                    "description": "Minimum snow fraction in the image to activate the pass 2 snow test.",
                    "id": "fsnow_total_lim",
                    "title": "The Fsnow_total_lim schema.",
                    "type": "number"
                },
                "fclear_lim": {
                    "default": 0.1,
                    "description": "Minimum clear pixel fraction in an elevation band to define zs.",
                    "id": "fclear_lim",
                    "title": "The Fclear_lim schema.",
                    "type": "number"
                }
            },
            "type": "object"
        },
        "fsc": {
            "id": "fsc",
            "properties": {
                "fscToc_Eq": {
                    "id": "fscToc_Eq",
                    "default": "0.5*tanh(2.65*ndsi-1.42)+0.5",
                    "description": "FscToc equation.",
                    "title": "the fscToc_Eq schema",
                    "type": "string"
                },
                "fscOg_Eq": {
                    "id": "fscOg_Eq",
                    "default": "fscToc/(1-tcd)",
                    "description": "FscOgequation.",
                    "title": "the fscOg_Eq schema",
                    "type": "string"
                },
                "tcd": {
                    "id": "tcd",
                    "default": "",
                    "description": "Raster map of th tree cover density coded in percent (0-100). Specific to H&R Snow & Ice parameter (generate the snow cover fraction in the binary snow mask)",
                    "title": "the tcd schema",
                    "type": "string"
                }
            }
        },
        "shaded_snow": {
            "id": "shaded_snow",
            "properties": {
                "detect_shaded_snow": {
                    "id": "detect_shaded_snow",
                    "default": true,
                    "description": "Activate shaded snow detection",
                    "title": "the detect_shaded_snow schema",
                    "type": "boolean"
                },
                "hillshade_lim": {
                    "id": "hillshade_lim",
                    "default": 0.2,
                    "description": "Hillshade threshold",
                    "title": "the hillshade_lim schema",
                    "type": "number"
                },
                "shaded_snow_pass": {
                    "id": "shaded_snow_pass",
                    "default": 160,
                    "description": "shaded snow threshold",
                    "title": "the shaded_snow_pass schema",
                    "type": "integer"
                },
                "rastertools_use": {
                    "id": "rastertools_use",
                    "default": true,
                    "description": "Activate rastertools hillshade detection",
                    "title": "the rastertools_use schema",
                    "type": "boolean"
                },
                "rastertools_window_size": {
                    "id": "rastertools_window_size",
                    "default": 1024,
                    "description": "Define size of tiles to distribute processing",
                    "title": "the rastertools_window_size schema",
                    "type": "boolean"
                },
                "rastertools_radius": {
                    "id": "rastertools_radius",
                    "default": null,
                    "description": "Max distance (in pixels) around a point to evaluate horizontal elevation angle",
                    "title": "the rastertools_radius schema",
                    "type": "boolean"
                }
            }
        },
        "water_mask": {
            "id": "water_mask",
            "properties": {
                "water_mask_path": {
                    "id": "water_mask_path",
                    "default": "",
                    "description": "Path to raster (must be geotiff file, ending with .tif) or shapefile (must be a shapefile, ending with .shp)",
                    "title": "the path schema",
                    "type": "string"
                },
                "water_mask_raster_values": {
                    "id": "water_mask_raster_values",
                    "default": [1],
                    "description": "List of values from water mask raster that are considered land water and must therefore be masked before snow processing. This option is unused if path input is a shapefile",
                    "title": "the raster_values schema",
                    "type": "array"
                }
            }
        },
        "inputs": {
            "id": "inputs",
            "properties": {
                "div_mask": {
                    "description": "Input other mask image for slope correction flag (optional in MASK directory for Theia product *DIV*.TIF).",
                    "id": "div_mask",
                    "title": "The div_mask schema.",
                    "type": "string"
                },
                "div_slope_threshold": {
                    "description": "Input threshold of div_mask image to determine the flag for slope correction (optional for Theia product).",
                    "id": "div_slope_thres",
                    "title": "The Div_slope_thres schema.",
                    "type": "int"
                },
                "cloud_mask": {
                    "description": "Input mask image (in MASK directory for Theia product).",
                    "id": "cloud_mask",
                    "title": "The Cloud_mask schema.",
                    "type": "string"
                },
                "dem": {
                    "description": "Input DEM with the same resolution and extent as the input image if preprocessing is deactivated.",
                    "id": "dem",
                    "title": "The Dem schema.",
                    "type": "string"
                },
                "green_band": {
                    "id": "green_band",
                    "properties": {
                        "no_band": {
                            "default": 1,
                            "description": "Green band number.",
                            "id": "noBand",
                            "title": "The Noband schema.",
                            "type": "integer"
                        },
                        "path": {
                            "description": "Path to input L2A image or L2A green band.",
                            "id": "path",
                            "title": "The Path schema.",
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                "red_band": {
                    "id": "red_band",
                    "properties": {
                        "no_band": {
                            "default": 1,
                            "description": "Red band number.",
                            "id": "noBand",
                            "title": "The Noband schema.",
                            "type": "integer"
                        },
                        "path": {
                            "description": "Path to input L2A image or L2A red band.",
                            "id": "path",
                            "title": "The Path schema.",
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                "swir_band": {
                    "id": "swir_band",
                    "properties": {
                        "no_band": {
                            "default": 1,
                            "description": "SWIR band number.",
                            "id": "noBand",
                            "title": "The Noband schema.",
                            "type": "integer"
                        },
                        "path": {
                            "description": "Path to input L2A image or L2A swir band.",
                            "id": "path",
                            "title": "The Path schema.",
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            },
            "type": "object"
        }
    },
    "type": "object"
}

=== eea/clms-hrwsi-system/HRWSI_Processing_Routines/HRWSI_NRT_Processing_Routines/fsc/let-it-snow-1.11.0/hpc/param20190612T31TCH.json
{
    "inputs": {
        "swir_band": {
            "path": "./input/SENTINEL2A_20190612-104918-663_L2A_T31TCH_C_V2-2/SENTINEL2A_20190612-104918-663_L2A_T31TCH_C_V2-2_FRE_B11.tif", 
            "noBand": 1
        }, 
        "red_band": {
            "path": "./input/SENTINEL2A_20190612-104918-663_L2A_T31TCH_C_V2-2/SENTINEL2A_20190612-104918-663_L2A_T31TCH_C_V2-2_FRE_B4.tif", 
            "noBand": 1
        }, 
        "cloud_mask": "./input/SENTINEL2A_20190612-104918-663_L2A_T31TCH_C_V2-2/MASKS/SENTINEL2A_20190612-104918-663_L2A_T31TCH_C_V2-2_CLM_R2.tif", 
        "green_band": {
            "path": "./input/SENTINEL2A_20190612-104918-663_L2A_T31TCH_C_V2-2/SENTINEL2A_20190612-104918-663_L2A_T31TCH_C_V2-2_FRE_B3.tif", 
            "noBand": 1
        }, 
        "div_mask": "./input/SENTINEL2A_20190612-104918-663_L2A_T31TCH_C_V2-2/MASKS/SENTINEL2A_20190612-104918-663_L2A_T31TCH_C_V2-2_MG2_R2.tif", 
        "dem": "/work/OT/siaa/Theia/Neige/DEM/S2__TEST_AUX_REFDE2_T31TCH_0001.DBL.DIR/S2__TEST_AUX_REFDE2_T31TCH_0001_ALT_R2.TIF", 
        "div_slope_thres": 64
    }, 
    "vector": {
        "generate_vector": false, 
        "generate_intermediate_vectors": false, 
        "gdal_trace_outline_dp_toler": 0, 
        "use_gdal_trace_outline": true, 
        "gdal_trace_outline_min_area": 0
    }, 
    "snow": {
        "fsnow_total_lim": 0.001, 
        "fsnow_lim": 0.1, 
        "dz": 100, 
        "ndsi_pass1": 0.4, 
        "ndsi_pass2": 0.15, 
        "red_pass1": 200, 
        "red_pass2": 40, 
        "fclear_lim": 0.1
    }, 
    "cloud": {
        "rm_snow_inside_cloud": false, 
        "rm_snow_inside_cloud_threshold": 0.85, 
        "strict_cloud_mask": false, 
        "rm_snow_inside_cloud_min_area": 5000, 
        "shadow_out_mask": 64, 
        "all_cloud_mask": 1, 
        "shadow_in_mask": 32, 
        "red_darkcloud": 300, 
        "red_backtocloud": 100, 
        "rf": 12, 
        "high_cloud_mask": 128, 
        "rm_snow_inside_cloud_dilation_radius": 1
    }, 
    "general": {
        "nb_threads": 1, 
        "multi": 10, 
        "ram": 2048, 
        "log": true, 
        "pout": "./output/", 
        "target_resolution": -1, 
        "nodata": -10000, 
        "preprocessing": false
    },
    "fsc": {
        "dofsc": true,
        "fscToc_Eq": "1.45*ndsi-0.01", 
        "fscOg_Eq": "fscToc/(1-tcd)",
        "tcd": "/work/OT/siaa/Theia/Neige/CoSIMS/data/TCD/TCD_2015_R2_T31TCH.TIF"
    }    
}
